{% set name = "kdeclarative" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kdeclarative-{{ version }}.tar.xz
  sha256: 387c41626c145ddd1fc76d102b5ceaf37321cd02ca7395a10084cfd009bd0422

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kdeclarative', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kio >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kpackage >={{ major_minor }}
    - kservice >={{ major_minor }}
    - kiconthemes >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kglobalaccel >={{ major_minor }}
    - kwindowsystem >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Declarative.so

about:
  home: https://api.kde.org/frameworks/kdeclarative/html/index.html
  license: GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-GPL AND LicenseRef-KDE-Accepted-LGPL AND LicenseRef-Qt-Commercial AND MIT AND Qt-LGPL-exception-1.1
  license_file:
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-GPL.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
    - LICENSES/LicenseRef-Qt-Commercial.txt
    - LICENSES/MIT.txt
    - LICENSES/Qt-LGPL-exception-1.1.txt
  summary: Integration of QML and KDE work spaces
  description: |
    KDeclarative provides integration of QML and KDE work spaces.
    It's comprises two parts: a library used by the C++ part of
    your application to intergrate QML with KDE Frameworks specific
    features, and a series of QML imports that offer bindings to some
    of the Frameworks.
  dev_url: https://cgit.kde.org/kdeclarative.git/tree

extra:
  recipe-maintainers:
    - scopatz
