{% set name = "kdeclarative" %}
{% set version = "5.70.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kdeclarative-{{ version }}.tar.xz
  sha256: 8914c2266d7ea32f8028aee13ae5a7f39a3583f7ec74a74584577fb0f2bc09ef

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kdeclarative', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kio >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kpackage >={{ major_minor }}
    - kservice >={{ major_minor }}
    - kiconthemes >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kglobalaccel >={{ major_minor }}
    - kwindowsystem >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Declarative.so

about:
  home: https://api.kde.org/frameworks/kdeclarative/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Integration of QML and KDE work spaces
  description: |
    KDeclarative provides integration of QML and KDE work spaces.
    It's comprises two parts: a library used by the C++ part of
    your application to intergrate QML with KDE Frameworks specific
    features, and a series of QML imports that offer bindings to some
    of the Frameworks.
  dev_url: https://cgit.kde.org/kdeclarative.git/tree

extra:
  recipe-maintainers:
    - scopatz
